# Generated by Django 5.2.12 on 2026-04-04 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=64, unique=True)),
                ('order_ref', models.CharField(db_index=True, max_length=64)),
                ('method', models.CharField(choices=[('pix', 'PIX'), ('counter', 'Balcão'), ('card', 'Cartão'), ('external', 'Externo')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('authorized', 'Autorizado'), ('captured', 'Capturado'), ('failed', 'Falhou'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado')], db_index=True, default='pending', max_length=20)),
                ('amount_q', models.BigIntegerField()),
                ('currency', models.CharField(default='BRL', max_length=3)),
                ('gateway', models.CharField(blank=True, default='', max_length=50)),
                ('gateway_id', models.CharField(blank=True, default='', max_length=200)),
                ('gateway_data', models.JSONField(blank=True, default=dict, help_text='Dados de resposta do gateway. Populado automaticamente. Ex: {"pix_qr_code": "00020126...", "txid": "abc123"}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authorized_at', models.DateTimeField(blank=True, null=True)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'intenção de pagamento',
                'verbose_name_plural': 'intenções de pagamento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('capture', 'Captura'), ('refund', 'Reembolso'), ('chargeback', 'Chargeback')], max_length=20)),
                ('amount_q', models.BigIntegerField()),
                ('gateway_id', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='payman.paymentintent')),
            ],
            options={
                'verbose_name': 'transação de pagamento',
                'verbose_name_plural': 'transações de pagamento',
                'ordering': ['-created_at'],
            },
        ),
    ]
